### ISSUE TITLE
Do not force cli args to "...-..." format

### ISSUE THREAD

**Issue by festeh** [Jeremy-Stafford/datacli#1]
Hi!

Thanks for that nice lib, very useful! The only issue I encountered so far is this line.
` yield "--" + field.name.replace("_", "-")`

Is there a reason to forbid underscores in cli args?

**Comment by Jeremy-Stafford** [comment]
The standard for long options is `--kebab-case`, so that is what `datacli` does. It is possible to change the field names using [data-class field metadata][metadata], but this feature is currently not mentioned in the documentation. I will add add it now.
 
[metadata]: https://docs.python.org/3/library/dataclasses.html#dataclasses.field
